### PR TITLE
Fixed popover

### PR DESCRIPTION
**Pull request by TechKat**
FA updated their code, modified code to reflect changes.

### CODE REVIEW

**Comment by Serofox** [comment]
Thanks for the PR... I realized I hadn't pushed my latest changes to GH after releasing the last version, can you rebase so that your commit is cleaner? Ty!

**Comment by TechKat** [comment]
@Serofox Rebase?

**Comment by Serofox** [comment]
As in rebase your changes on master: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by TechKat** [comment]
It is on master?

**Comment by Serofox** [comment]
You'll need to re-pull and rebase, I updated master with what was published to the chrome extension marketplace/store

**Comment by Furchee** [comment]
Thank you for the fix!
I'm using this until it's fixed in the store page.

**Comment by TechKat** [comment]
I'll rebase :)

**Pull request closed without merging**
